# Gems
gems:
 - jekyll-paginate
 - jekyll-gist
 - redcarpet

# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Fist of Life  
tagline:          ''
description:      '2017 Development Hub'
url:              https://teamresistance.github.io/
baseurl:          /fist-of-life

authors:
  rothso:
    name:         'Rothanak So'
    url:          https://github.com/rothso

paginate:         5

excerpt_separator: <!--more-->

# Custom vars
version:          0.1-alpha

github:
  repo:           https://github.com/teamresistance/fist-of-life
